Area measurment Mesh Generation
Euclideon/vaultclient pull request #1017
Opened 2020-09-04 06:01 UTC by Jossos

- Implemented Area Measurement Mesh Generator
- Fixes AB#1980
- Fixes AB#1769

2020-09-29 04:32 UTC, peterAdams1014 requested changes

2020-09-29 04:32 UTC, peterAdams1014 commented on src/scene/vcPOI.cpp
> +                  udDouble3 newPointPosition;
`newPointConnection` can be removed.

2020-09-29 04:32 UTC, peterAdams1014 commented on src/scene/vcPOI.cpp
> +    double angle = -atan2(pos.y - target.y, pos.x - target.x);
`udAtan2()`

2020-09-29 04:32 UTC, peterAdams1014 commented on src/scene/vcPOI.cpp
> +      if (udMag2(curPointPos2 - prevPointPos2) < UD_EPSILON
Not sure how often this runs, but potential optimization could be done here:

`udMagSq2() < UD_EPSILON * UD_EPSILON`

2020-09-29 04:32 UTC, peterAdams1014 commented on src/scene/vcPOI.cpp
> +      double dist = udMag2<double>(pos - triPoint2);
Compare squared values here.

2020-09-29 04:40 UTC, Jossos commented on src/scene/vcPOI.cpp
> +                  udDouble3 newPointPosition;
newPointPosition*

2020-10-07 02:52 UTC, peterAdams1014 approved these changes

2020-10-07 02:52 UTC, merged