Added show angles option to line and area tools
Euclideon/vaultclient pull request #1020
Opened 2020-09-07 04:47 UTC by int-Frank

Fixes AB#1837

2020-09-07 05:50 UTC, jproust commented
![Angles_issue](https://user-images.githubusercontent.com/17191283/92352153-cbe12980-f120-11ea-91e7-40e905fb225d.png)
What side is the 177.27 deg angle

2020-09-07 06:33 UTC, int-Frank commented
> ![Angles_issue](https://user-images.githubusercontent.com/17191283/92352153-cbe12980-f120-11ea-91e7-40e905fb225d.png)
> What side is the 177.22 deg angle

I use the  _smallest_ angle between the lines. Or in other words, the inverse cosine of the dot product between the vectors of the two lines.

2020-09-07 10:42 UTC, jproust commented
> I use the _smallest_ angle between the lines. Or in other words, the inverse cosine of the dot product between the vectors of the two lines.

I know I have read your code, I just find the display of the angle a bit confusing when it's close to 180° as the user can't really know which side the angle is. It can be confusing if for instance the smallest angle is an angle in the z plane and the user is watching from above.
Anyway we can display the measured angle ?
![angle_issue](https://user-images.githubusercontent.com/17191283/92379302-93eedc00-f14a-11ea-8691-ba2a8d6bfed5.png)

2020-09-07 14:12 UTC, OsiJr commented on src/scene/vcPOI.cpp
> +        udProjectNode_SetMetadataBool(m_pParent->m_pNode, "showAngles", m_pParent->m_showAngles);
`OnNodeUpdate` doesn't load this key (there is a helper in vcProject for bools)

2020-09-07 14:13 UTC, OsiJr requested changes
Will need to load the show angles setting

2020-09-07 22:05 UTC, int-Frank commented
@jproust Ah I see. Perhaps I could render a little angle symbol between the lines. Something like 
![image](https://user-images.githubusercontent.com/7401740/92418231-cc71d280-f1a9-11ea-8453-8b2f261e3899.png)
 @OsiJr What do you think?

2020-09-08 02:34 UTC, OsiJr approved these changes

2020-09-08 02:35 UTC, OsiJr approved these changes

2020-09-08 02:35 UTC, merged