Changed default DEM server to ESRI
Euclideon/vaultclient pull request #1088
Opened 2020-09-21 04:05 UTC by peterAdams1014

Added required LercLib (CntZ image format reading).
Changes to DEM tile loading to support tile 'not available' state.

2020-09-21 04:16 UTC, samsinsane requested changes
As discussed on Teams, you need to add the third party license information to `vcThirdPartyLicenses.h`.

2020-09-21 04:16 UTC, samsinsane commented on project.lua
> +    files { "3rdParty/LercLib/**.h","3rdParty/LercLib/**.hpp", "3rdParty/LercLib/**.cpp" }
We use tabs in Lua files.

2020-09-22 00:10 UTC, OsiJr requested changes
Need attribution and third party for LERC lib

2020-09-22 01:50 UTC, samsinsane approved these changes

2020-09-22 02:10 UTC, OsiJr approved these changes

2020-09-22 02:10 UTC, merged