Added a maximum tile skirt length.
Euclideon/vaultclient pull request #1120
Opened 2020-09-24 00:36 UTC by peterAdams1014

2020-09-24 01:03 UTC, OsiJr requested changes

2020-09-24 01:03 UTC, OsiJr commented on src/rendering/vcTileRenderer.cpp
> +  const float EarthRadius = 6378137.0f; // TODO: Read this in
This TODO is important enough to do now. The next sprint has non-earth planets that will break this immediately.

2020-09-24 22:19 UTC, Jossos commented on src/rendering/vcTileRenderer.cpp
> +  float tileSkirtLength = udClamp((float)pTileRenderer->cameraDistanceToSurface, 8000.0f, halfEarthRadius);
so you no longer need to add 8000.0f to pTileRenderer->cameraDistanceToSurface?

2020-09-25 01:00 UTC, OsiJr approved these changes

2020-09-25 01:00 UTC, merged