Added some parameters for boxes
Euclideon/vaultclient pull request #1186
Opened 2020-10-13 09:18 UTC by asunawu

Added -region 0.0 0.0 0.0 1.0 1.0 1.0(min x, y, z and max x, y, z) to runtime parameters of vcConvertCMD.

2020-10-14 02:26 UTC, samsinsane requested changes
You need to add this into the `vcConvertCMD_ShowOptions` display too.

2020-10-14 03:09 UTC, asunawu commented
Added.

2020-10-14 07:22 UTC, OsiJr submitted a review, later dismissed

2020-10-16 00:51 UTC, samsinsane approved these changes

2020-10-16 00:51 UTC, merged