Converting tiff now supports a lot more of the tif spec
Euclideon/vaultclient pull request #1196
Opened 2020-10-15 05:08 UTC by int-Frank

Fixes AB#2334 

Supports a lot more of the tiff spec, but does not yet support geotiff. Currently supports:
 - pulling all images from all internal directories
 - general image loading
 - optimised loading tiled image data
 - 1, 2, 4, 8, 16, 32 and 64-bit uint samples (pixel channels)
 - 2, 4, 8, 16, 32 and 64-bit int samples
 - 32 and 64-bit float samples
 - up to 4 samples per pixel
 - Grey scale images 
 - RGB images
 - Palettized images
 - Samples stored contiguous or separately

2020-10-16 01:22 UTC, samsinsane requested changes
Reconsider all usages of the libtiff allocation system - it's only necessary to use if libtiff is going to provide or free the pointers at some point.

2020-10-16 01:22 UTC, samsinsane commented on src/vcTiffConvert.cpp
> +    // Currently do not support 16-bit floats
Just an FYI, I believe there's a function that can pack and/or unpack 16bit floats in udStream already. This is used for the 16bit float on the graphics card - I'm confident it won't be immediately usable for you though, so not a required change for this PR.

2020-10-16 01:22 UTC, samsinsane commented on src/vcTiffConvert.cpp
> +    pBuf = (uint8 *)_TIFFmalloc(TIFFTileSize(pData->pTif)); // TODO could allocated this once per image
Given that this function frees `pBuf`, is there any reason to use `_TIFFmalloc` over `udAllocType` here?

2020-10-16 01:22 UTC, samsinsane commented on src/vcTiffConvert.cpp
> +  _TIFFfree(pData->tile.pRaster);
Is there a case where this isn't allocated by your code above? Seems like using `udAllocType` would be superior in this case.

2020-10-16 01:22 UTC, samsinsane commented on src/vcTiffConvert.cpp
> +  TIFF *pTif;
Doesn't make a huge amount of sense to rename this from `pTiff`, it results in a number of lines changing and is kind of less clear. Is a TIF different to a TIFF?

2020-10-16 01:22 UTC, samsinsane commented on src/vcTiffConvert.cpp
> +static udError vcTiff_SampleDataToColour(vcTiffImageFormat const & format, vcTiffSampleData const & data, uint32_t *pColour)
Both `*` and `&` go with the variable name, this happens in a few other functions. You may need to adjust your Visual Studio settings if this is automatically happening.

2020-10-21 01:22 UTC, OsiJr approved these changes

2020-10-21 01:22 UTC, merged