Added a 'geoverse style map mode' for the 2nd viewport
Euclideon/vaultclient pull request #971
Opened 2020-08-24 07:39 UTC by peterAdams1014

Some viewport settings are now serialized.
Euclideon watermark is now only rendered on the first viewport.
Moved the initial project blank scene creation to a more appropriate place in program start up.

2020-08-24 07:54 UTC, samsinsane requested changes

2020-08-24 07:54 UTC, samsinsane commented on builds/assets/lang/enAU.json
> +  "orthographicCameraViewport": "Orthographic Second Camera (Geoverse style)",
Should this reference Geoverse?

2020-08-24 07:54 UTC, samsinsane commented on src/scene/vcViewpoint.cpp
> +  for (int viewportIndex = 0; viewportIndex < pProgramState->settings.activeViewportCount; ++viewportIndex)
Can you remove the wrong for loop?

2020-08-24 07:54 UTC, samsinsane commented on src/vcSettings.cpp
> +      pSettings->viewports[viewportIndex].resolution.y = data.Get("viewports.viewport[% d].height", viewportIndex).AsInt(128);
This can't be working with `% d` instead of `%d`?

2020-08-25 00:27 UTC, peterAdams1014 commented on builds/assets/lang/enAU.json
> +  "orthographicCameraViewport": "Orthographic Second Camera (Geoverse style)",
Probably not.

2020-08-25 00:27 UTC, peterAdams1014 commented on src/scene/vcViewpoint.cpp
> +  for (int viewportIndex = 0; viewportIndex < pProgramState->settings.activeViewportCount; ++viewportIndex)
Ah! Mangled merge. Good catch.

2020-08-25 01:09 UTC, samsinsane approved these changes

2020-08-25 01:10 UTC, merged